version: '3.8'

services:
  auth-app:
    build: ../auth-app
    ports:
      - "4000:4000"
    env_file:
      - ../auth-app/.env
    depends_on:
      - db

  api-app:
    build: ../api-app
    ports:
      - "5000:5000"
    env_file:
      - ../api-app/.env
    depends_on:
      - db
      - auth-app

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
